### PR TITLE
Depot

### PR DESCRIPTION
**Pull request by Manuzor**
_Note: I'm not merging to `master` but `server`_

Introducing the `depot` command which is responsible for storing (uploading) a pastry in (to) the shop (server).

Usability of this thing will have to improve, but this should be done later, once we have a better idea of the workflow in our little bakery system.

### CODE REVIEW

**Comment by pampersrocker** [comment]
I thought about the whole upload and download process and I think it would be way better to create a zip or tarball or whatever of the uploaded files and upload this one instead of each file individually.
Especially when uploading lots of code files this saves a lot of bandwidth because especially these can be compressed at a very good rate.

**Comment by Manuzor** [comment]
Sounds good. So I assume the oven should create these zip files and call them `pastry.zip`? :smile:

**Comment by Manuzor** [comment]
Creating zip files using python looks easy enough. I will update oven and depot accordingly, if you agree.

**Comment by pampersrocker** [comment]
:+1:

**Comment by Manuzor** [comment]
Using [zipfile](https://docs.python.org/3/library/zipfile.html), we have a couple of compression options. Here's some data for ezEngine milestone-6 VS2013 64 bit (only):
* LZMA: 33,2 MB
* BZIP2: 42,9 MB
* DEFLATED: 50,6 MB
* STORED: 200 MB

Obviously, the stronger the compression, the longer it takes. Should I just always use LZMA? Or should this be an option? Or maybe I should just go with DEFLATED, because it is still really good and quite fast.

**Comment by pampersrocker** [comment]
Sadly it seems to be currently impossible to set the compression level of lzma using `zipfile`. Usually you can set a value between 0 and 9. I've used lzma all the time and never had problems with it.

**Comment by Manuzor** [comment]
I have adjusted the `shop` on the `depot` branch, so be aware when working there. I've also completed the changes to sending only a single _.zip_ file instead of all files individually. So maybe review the stuff again and merge it in?

**Pull request merged**
