### PR TITLE
Oven

### PR DESCRIPTION
**Pull request by Manuzor**
I think this can be merged back to master now.

Someone review the code please. :smiley:

### CODE REVIEW

**Comment by Manuzor** [comment]
New commit makes the oven more flexible. The user can now supply a custom function to decide what actually happens to the ingredients. By default, the `pastry.json` is written.

**Comment by pampersrocker** [comment]
An entry currently looks like this for a header file:
```json
{
   "path": "Code/Engine/Core/Application/Application.h",
   "platform": {
    "bits": 64,
    "config": "Debug",
    "detailed_name": null,
    "generator": null,
    "name": "all",
    "user_data": null
   },
   "tags": [
    "header-file"
   ]
}
```

This gives very little information about the platform but creates a lot of boilerplate (the whole files has more the 6k lines). Wouldn't it be better to suppress not used platform arguments in the output?

**Comment by Manuzor** [comment]
Well I thought that we'd have a "all plattforms" instance, which is currently set to the values you see. We could also use `None` as the indicator that all platforms are supported.

**Comment by pampersrocker** [comment]
Or even leave out the whole platform entry when this will be included in all platforms

**Comment by Manuzor** [comment]
I took this idea further and implemented key-value tags now, i.e. instead of a list of strings, tags are now a dict with string keys and arbitrary values. How that'll work on the server side... I don't know, quite frankly :D but we'll figure that out. In the worst case, all platform properties will become their own tag-key. Anyway, ingredients now only have a path and the tag-dict.

**Comment by pampersrocker** [comment]
@Manuzor  Can you modify the ezEngine recipe to the new tags, so I can test it?

**Comment by Manuzor** [comment]
Oops, only did that locally :P

**Comment by Manuzor** [comment]
There you go.

**Comment by pampersrocker** [comment]
:+1:

**Pull request merged**
